backend:
  name: 'github'
  repo: 'xbmc/kodi-tv'
  branch: 'main'

site_url: 'https://kodi-tv.netlify.app'
media_folder: '/static/images/blog'
public_folder: '/images/blog'
publish_mode: 'editorial_workflow'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/article'
    create: true
    path: '{{title}}/index'
    slug: 'index'
    preview_path: '/article/{{title}}'
    media_folder: '/static/images/blog'
    public_folder: '/images/blog'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string', required: false  }
      - name: 'featured_image'
        label: 'Featured Image'
        widget: 'object'
        collapsed: true
        summary: '{{fields.src}}'
        fields:
          - {name: 'src', label: 'Image', widget: 'image'}
          - {name: 'title', label: 'Title', widget: 'string'}
          - {name: 'alt', label: 'Alt text', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'store'
    label: 'Store'
    extension: 'yaml'
    folder: '/src/data/yaml/store'
    create: true
    path: '{{name}}'
    slug: '{{name}}'
    show_preview_links: false
    media_folder: '/static/images/store'
    public_folder: '/images/store'
    fields:
      - { label: 'Item', name: 'name', widget: 'string' }
      - { label: 'URL', name: 'slug', widget: 'string' }
      - { label: 'Group Number', name: 'group_number', widget: 'number' }
      - { label: 'Image', name: 'icon', widget: 'image' }
