backend:
  name: github
  repo: xbmc/kodi-tv
  branch: main

site_url: https://kodi-tv.netlify.app
media_folder: /static/images/blog
public_folder: /images/blog
publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/article'
    create: true
    path: '{{title}}/index'
    slug: 'index'
    preview_path: '/article/{{title}}'
    media_folder: '/static/images/blog'
    public_folder: '/images/blog'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string', required: false  }
      - name: 'featured_image'
        label: 'Featured Image'
        widget: 'object'
        collapsed: true
        summary: 'Featured Image'
        fields:
          - {name: src, label: Image, widget: image}
          - {name: title, label: Title, widget: string}
          - {name: alt, label: Alt text, widget: string}
      - { label: 'Body', name: 'body', widget: 'markdown' }
