backend:
  name: github
  repo: xbmc/kodi-tv
  branch: main

site_url: https://kodi-tv.netlify.app
media_folder: /static/images/blog
public_folder: /images/blog
publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/article'
    create: true
    path: '{{title}}/index'
    slug: 'index'
    preview_path: '/article/{{slug}}'
    media_folder: '/static/images/blog'
    public_folder: '/images/blog'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string', required: false  }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
